---
title: "Untitled"
author: "Ancel Chong Fu Shea"
date: "3/16/2023"
output: html_document
---

## R Markdown

## Set up
```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(scales)
library(ggplot2)
library(lubridate)
library(gridExtra)
library(ncdf4)

#change data path as necessary..
path <- '/Users/nicholaschan/Documents/GitHub/MH3511-proj/data'
```

## Reading Data (what data is this)
```{r}

setwd(path)

data <- read.csv('historical-daily-weather-records.csv')

head(data)

data$date<-as.Date(data[,1])

monthly <- group_by(data,month = lubridate::floor_date(date, 'month')) 

```

## Reading SG Surface Air Temp data
```{r}

setwd(path)

sat <- read.csv('surface-air-temperature-monthly-mean.csv')

sat[,1]<-as.Date(paste(sat[,1], "-01", sep=""))

#getting reference range..
sat.ref <- sat[sat$month >= as.Date('1980-01-01') & sat$month <= as.Date('2010-12-31'),]

#calculate avg temp/month in ref period to act as a baseline for anomalies..
sat.ref <- sapply(1:12, function(m){
  avg.temp <- round(mean(sat.ref[which(month(sat.ref$month)==m),]$mean_temp),4)
  
})
sat.new <- sat[sat$month >= as.Date('2011-01-01'),]

#calculating sat anomalies from 2011 onwards..
sat.anom<- data.frame(month = sat.new$month,
                        anom = sapply(1:nrow(sat.new),function(i){
                        
                        #sat on a specific month - sat in ref period of the same month..
                        anomaly <- sat.new$mean_temp[i]-sat.ref[month(sat.new$month[i])]
                          
                        }))

ggplot(sat) + 
  geom_point(aes(x=month, y = mean_temp)) + 
  geom_line(aes(x=month, y = mean_temp))

```

## Reading monthly SG rainfall data
```{r}
setwd(path)

#reading rainfall data..
rainf <- read.csv('rainfall-monthly-total.csv')

rainf[,1]<-as.Date(paste(rainf[,1], "-01", sep=""))

#getting reference range for rainfall..
rainf.ref <- rainf[rainf$month >= as.Date('1980-01-01') & rainf$month <= as.Date('2010-12-31'),]

#calculate avg rainf/month in ref period to act as a baseline for anomalies..
rainf.ref <- sapply(1:12, function(m){
  avg.rainf <- round(mean(rainf.ref[which(month(rainf.ref$month)==m),]$total_rainfall),4)
})

#find rainfall data period of interest, 2011 onwards..
rainf.new <- rainf[rainf$month >= as.Date('2011-01-01'),]

#caluclating rainfall anomalies from 2011..
rainf.anom<- data.frame(month = rainf.new$month,
                        anom = sapply(1:nrow(rainf.new),function(i){
                        
                        #rainfall on a specific month - rainfall in ref period of the same month
                        anomaly <- rainf.new$total_rainfall[i]-rainf.ref[month(rainf.new$month[i])]
                          
                        }))

#plotting scatter and line plots
ggplot(rainf) + 
  geom_point(aes(x=month, y = total_rainfall)) + 
  geom_line(aes(x=month, y = total_rainfall))

```

## Reading SST data in pacific..
```{r}
setwd(path)

#read sst data
sst <- read.table('sstoi.indices.txt',header=T)

#finding ref range 1980-2010
sst.ref <- sst[sst$YR >= 1980 & sst$YR <= 2010,]

#sst baseline per month
sst.ref <- sapply(1:12, function(m){
  avg.sst <- round(mean(sst.ref[which(month(sst.ref$MON)==m),]$NINO3.4),4)
})

#sst range for 2011 onwards, data that matters
sst.new<- sst[sst$YR >= 2011,]

# finding anomaly with fixed dates. assume data was with respect to first day of the month
# note the data has anomaly values bur wrt to 1990-2020.
sst.anom<- data.frame(month = as.Date(paste(sst.new$YR,sst.new$MON,'01',sep='-')),
                        anom = sapply(1:nrow(sst.new),function(i){
                        
                        #sst on a specific month - sst in ref period of the same month
                        anomaly <- sst.new$NINO3.4[i]-sst.ref[sst.new$MON[i]]
                          
                        }))

#remove duplicate data
dupes <- duplicated(sst.anom$month)
sst.anom <- subset(sst.anom,!dupes)
  
```

## Plotting scatter plots of SST with SG SAT and Rainfall

```{r}
df_plot <- data.frame(date = sst.anom$month,
                      sst_anom = sst.anom$anom,
                      sat_anom=sat.anom$anom,
                      rainf_anom=rainf.anom$anom)

#calculate correlation
sst.sat.corr <- cor(df_plot$sst_anom,df_plot$sat_anom)
sst.rainf.corr <- cor(df_plot$sst_anom,df_plot$rainf_anom)

df_corr <- data.frame(sst.sat.corr,sst.rainf.corr)

print(df_corr)

#scatter plots
ggplot(df_plot,aes(x=rainf_anom))+
  geom_point(aes(y=sst_anom,color='sst.rainf'))+
  scale_color_manual(values=c('sst.rainf'='pink'))+
  ggtitle('Monthly SG rainfall anomaly againt SST anomaly from Jan 2011- Feb 2023')

ggplot(df_plot,aes(x=sat_anom))+
  geom_point(aes(y=sst_anom,color='sst.sat'))+
  scale_color_manual(values=c('sst.sat'='lightblue'))+
  ggtitle('Monthly SG SST anomaly againt SST anomaly from Jan 2011- Feb 2023')


```

## Reading Sub Surface Temp data
```{r}

months <- 01:12

years <- 1980:2022

substemp.folder <- '/subsurfacetempfiles'

substemp.file <- 'EN.4.2.2.f.analysis.g10.'

#extracting subsurface data from netcdf files
substemp <- lapply(1:length(years),function(i){
  
  setwd(paste(path,substemp.folder,sep=''))
  
  monthly <- lapply(1:length(months),function(k){
    
    if(months[k]<10){
      data <- nc_open(paste(substemp.file,years[i],'0',months[k],'.nc',sep=''))
    }
    else{
      data <- nc_open(paste(substemp.file,years[i],months[k],'.nc',sep=''))
    }

    
  })
  
})

#finding the mean temp at each month and each year
substemp.mean <- sapply(1:length(substemp),function(j){
  
  monthly <- sapply(1:length(months),function(n){
    
    #finding all the temperature data
    data.temp <- (ncvar_get(substemp[[j]][[n]],'temperature'))
    
    #mean the monthly temp in the area of interest, lon 190-240 (-170,-120), lat 78-88 (-5,5)
    month.temp <- mean(data.temp[190:240,78:88,],na.rm=T)
  
})
    
})

#convert celsius
substemp.mean <- substemp.mean-273.15

# start from 32 because that corresponds to 2011. Columns are years
substemp.anom <- sapply(32:ncol(substemp.mean),function(c){
  
  substemp.ref <- sapply(1:nrow(substemp.mean),function(r){
    
    #index 1:30 for the reference of 1980-2010.
    anom <- substemp.mean[r,c]-mean(substemp.mean[r,1:30])
    
  })
  
})

#turn matrix to vector for ease of access
substemp.anom.vec <- as.vector(substemp.anom)

```

## Correlate Sub Surface temp with SG Rainfall & SAT
```{r}
#set upper limit on data so reduce data length
df_plot2 <- data.frame(substemp_anom = substemp.anom.vec,
                      sat_anom=sat.anom[1:144,2],
                      rainf_anom=rainf.anom[1:144,2])

#calculate correlation
subs.sat.corr <- cor(df_plot2$substemp_anom,df_plot2$sat_anom)
subs.rainf.corr <- cor(df_plot2$substemp_anom,df_plot2$rainf_anom)

df_corr2 <- data.frame(subs.sat.corr,subs.rainf.corr)

print(df_corr2)

#scatter plots
ggplot(df_plot2,aes(x=rainf_anom))+
  geom_point(aes(y=substemp_anom,color='subs.rainf'))+
  scale_color_manual(values=c('subs.rainf'='pink'))+
  ggtitle('Monthly Sub Surf Temp anomaly againt SG Rainfall from Jan 2011- Dec 2022')

ggplot(df_plot2,aes(x=sat_anom))+
  geom_point(aes(y=substemp_anom,color='subs.sat'))+
  scale_color_manual(values=c('subs.sat'='lightblue'))+
  ggtitle('Monthly Sub Surf Temp anomaly againt SG SAT anomaly from Jan 2011- Dec 2022')

ggplot(df_plot2,aes(x=1:nrow(df_plot2)))+
  geom_line(aes(y=substemp_anom,color='subs'))+
  geom_line(aes(y=sat_anom,color='sat'))+
  #geom_line(aes(y=rainf_anom,color='rainf'))+
  scale_color_manual(values=c(subs='red',sat='lightgreen','rainf'='lightblue'))

fakesat <- df_plot2$sat_anom[5:nrow(df_plot2)]
fakesub <- df_plot2$substemp_anom[1:(nrow(df_plot2)-4)]

ggplot()+
  geom_line(aes(x=1:140,y=fakesub,color='subs'))+
  geom_line(aes(x=1:140,y=fakesat,color='sat'))+
  scale_color_manual(values=c(subs='red',sat='lightgreen','rainf'='lightblue'))

```